### ISSUE TITLE
Prepare presentation

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#106]
### Grade Value  (5 of total 40 points of the course)

- Entire course is worth 40 points
- Combined Presentations are worth 10 points
- November 8th presentation is worth 5 points of your total 40 points.
 
### Duration

- 15 minutes per group, with about 5 minutes between the individual groups for questions and changes.

 
### Format

- Short description of problem and solution

1. Problem from a user’s perspective
2. Solution from a technical perspective
3. Solution from a methodology perspective

- Description of what has been realized so far

1. If possible with short demonstration

- Conclusion and Outlook

1. User’s perspective
2. Technical perspective
3. Methodology
 
### Evaluation Criteria

- Contents
1. Relevant, technically correct, argumentatively supported and testify to an in-depth examination of the topic.

- Structure

1. The presentation is well structured and the parts are coordinated.

- Media

1. Illustrative material is attractive and carefully prepared. Media are used professionally.

- Language

1. The style and manner of speaking are persuasive and contribute to understanding.

 
### SCRUM
 
With regards to Scrum, you should attempt to integrate information into the presentations.  Include description  of methods used, what has worked, what has changed, and what might be improved going forward.
 
SCRUM topics for consideration

- Review of the project setup: recording the initial situation, topic analysis, stakeholder (management), organization, installations, etc.
- Review: Product goal achieved? sprint goals? demarcation? Deliverables created? Product Backlog / Sprint Backlog
- Retrospective I: Scrum Method: Scrum Roles (Product Owner, Scrum Master, Developer), Scrum Events and Scrum Artifacts.
- Retrospective II: Tools/Instruments: Insights into the use of tools (GitLab/GanttLab); communication (teams, etc.); Controlling (burndown chart, etc.).
- Lessons learned (team + personal): Insights into framework conditions, cooperation (in a team, specialist supervisor, PM coach, customer, operator, etc.)

### Notes from Moodle:

Rahmenbedingungen:
* Präsentationsdauer pro Gruppe ist 20 Minuten. Planen Sie dabei aber etwas Zeit ein für Fragen / Diskussionen.
* Grundsätzlich sollen sich alle Gruppenmitglieder aktiv an der Präsentation beteiligen. 
* Während der Präsentation bitte Kamera einschalten.
* Bitte verfolgen Sie auch die Präsentationen der anderen Gruppen Ihrer jeweiligen Session.

Ziel der Präsentation ist es, Folgendes zu zeigen:
* Was ist die Problemstellung Ihres Projektes?
(Zielsetzungen, Anforderungen, Rahmenbedingungen)
* Wie wollen Sie die Problemstellung lösen?
(Architektur, Datenmodell, Prozessmodell, Technologien, usw.)
* Wie setzen Sie das Projekt mit Scrum um?

Die Präsentationen werden nach folgenden Kriterien beurteilt:
* **Inhalte**: Sind relevant, fachlich korrekt, argumentativ gestützt und zeugen von einer vertieften Auseinandersetzung mit dem Thema.
* **Aufbau**: Präsentation ist gut gegliedert und die Teile aufeinander abgestimmt.
* **Medien**: Anschauungsmaterial ist attraktiv und sorgfältig erstellt. Medien werden professionell eingesetzt.
* **Sprache**: Sprachstil und Sprechweise sind überzeugend und tragen zum Verständnis bei.

Bezüglich Scrum kommen die nachfolgenden Beurteilungskriterien zur Anwendung. Die entsprechenden Informationen sind in die Präsentation zu integrieren.
**Wichtig**: Weil Herr Helbling nicht alle Präsentationen mitverfolgen kann, erstellen Sie bitte ein PDF-Dokument, aus welchem die entsprechenden Informationen ersichtlich sind. Senden Sie das Dokument bitte vorgängig per Mail an Hr. Helbling (frank.helbling@bfh.ch).

* **Ausgangslage**: Die Situation (inkl. Problem/Chance/Zwang) wird in Bezug auf das Thema allgemeinverständlich analysiert. Die Stakeholder sind benannt. Allfällige Hypothesen sind formuliert.
* **Produktziel**: Das Ziel des Lieferobjektes wurde festgelegt. Es erlaubt eine Beurteilung der Zielerreichung. Eine Abgrenzung ist erfolgt.
* **Scrum-Rollen**: Die Scrum-Rollen (Product Owner, Scrum Master, Developer) sind sinnvoll zugeordnet. Allfällige weitere Rollen (Kunde, Betreiber, etc.) sind festgelegt.
* **Sprintziel**: Das Ziel des Sprints bzw. Inkrements wurde adäquat definiert.
* **Anforderungen**: Das Backlog und das Sprint Backlog sind vorhanden und Scrum kompatibel aufgebaut. Es sind Epics oder Use Cases definiert.
* **Scrum Adaptionen**: Das Vorgehensmodell Scrum wurde methodisch sinnvoll an die Rahmenbedingungen angepasst. Die Methode wurde kritisch angewandt.

**Comment by janfuhrer** [comment]
Link to presentation on Figma: https://www.figma.com/file/EvP4l36NmE3nCAXIKDNvs8/Intermediate-Presentation?node-id=0%3A1
