### ISSUE TITLE
[Sub][UI] Create dashboard view

### ISSUE THREAD

**Issue by Andy-Bigler** [bfhmea4/mea4_01_habits#110]

**Comment by janlauber** [comment]
![image](https://user-images.githubusercontent.com/31922734/200056483-907a0104-5fa1-454d-9fc5-6b4063d03604.png)

**Comment by janlauber** [comment]
![image](https://user-images.githubusercontent.com/31922734/200056862-279f7275-e74a-4386-81b8-05334033ee30.png)

**Comment by janlauber** [comment]
with scroll:
![image](https://user-images.githubusercontent.com/31922734/200056927-4072910d-4818-41b4-99dd-853748f29771.png)
