### ISSUE TITLE
[Sub][UI] Create delete habit component

### ISSUE THREAD

**Issue by Andy-Bigler** [bfhmea4/mea4_01_habits#113]

**Comment by janlauber** [comment]
![image](https://user-images.githubusercontent.com/31922734/200017719-f874ffa3-5334-4b54-b137-86edeaa02748.png)

**Comment by janlauber** [comment]
![image](https://user-images.githubusercontent.com/31922734/200017752-6b08f7f2-740a-4947-98ee-f070193c6db7.png)
