### ISSUE TITLE
Setup OpenApi documentation

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#115]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [x] Story is reviewed and accepted by PO
- [x] Story is tested by DEV-Engineer
- [x] Documentation extended if required

---

**Business value**
As a developer, I want to see which endpoints exists, so that I can implement them in the frontend.

**Description**

**Open points**

**Preconditions**

**Acceptance criterias**
- OpenApi documentation works

**Not in scope**

**Implementation details**

**Test case description**
Not needed.

**Involved contacts**
PO: @Andy-Bigler  
TE: @janlauber

**Comment by Andy-Bigler** [comment]
![image](https://user-images.githubusercontent.com/17875084/206847140-9cc54e80-72d1-46b3-bede-b671eb5ba94c.png)

**Comment by Andy-Bigler** [comment]
http://localhost:8080/api/swagger-ui/index.html
