### ISSUE TITLE
Integrate select component for standalone journal entry creation

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#150]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [ ] Story is reviewed and accepted by PO
- [x] Story is tested by DEV-Engineer
- [x] Documentation extended if required

---

**Business value**
As a user, I want to create a log entry from the log view, so that I can add my missed entires.

**Description**
Create component to add log entries.

**Open points**

**Preconditions**

**Acceptance criterias**
- Creation without linked habit is possible

**Not in scope**

**Implementation details**
The select component is already created and can be used.

**Test case description**
Not needed.

**Involved contacts**
PO: @tonymowers 
TE: @janlauber

**Comment by Andy-Bigler** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/17875084/203961598-94e67a47-3f50-4187-a6d4-5c4762267dce.png">

**Comment by janlauber** [comment]
![image](https://user-images.githubusercontent.com/31922734/204140156-be8a83f6-ca30-4fdf-a3ec-c0017f3e04ed.png)
