### ISSUE TITLE
Better input validation

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#151]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [ ] Story is reviewed and accepted by PO
- [x] Story is tested by DEV-Engineer
- [x] Documentation extended if required

---

**Business value**
As a user, I want to see if my input is not valid, so that I can change it before sending it to the website.

**Description**
Validate user input and show feedback.

**Open points**

**Preconditions**

**Acceptance criterias**
- If a required field is not filled out a message is shown

**Not in scope**

**Implementation details**

**Test case description**
Not needed.

**Involved contacts**
PO: @tonymowers 
TE: @janlauber

**Comment by janlauber** [comment]
Improved several input validations:
- if habit of journal was deleted, you cannot edit the journal entry anymore
- when updating a habit, it only creates a CRUD operation if something actually changed
- Required input fields are now actually required and a toast message will be shown to a user to give feedback

**Comment by janlauber** [comment]
@Andy-Bigler check last task
