### ISSUE TITLE
Show a score for each habit based on the frequency goal

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#168]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [ ] Story is reviewed and accepted by PO
- [ ] Story is tested by DEV-Engineer
- [ ] Documentation extended if required

---

**Business value**
As a user, I want to see how good I'm performing for a habit, so that I get motivated to do it.

**Description**

**Open points**

**Preconditions**

**Acceptance criterias**
- Score is shown in the frontend
- Score is calculated in the backend
- Figma Prototyp is created

**Not in scope**

**Implementation details**

**Test case description**
Not needed.

**Involved contacts**
PO: @Andy-Bigler  
TE: @Andy-Bigler

**Comment by janlauber** [comment]
implemented the following:
![image](https://user-images.githubusercontent.com/31922734/208243573-284210af-bb4e-4dfb-968b-f479c6c0cf40.png)
