### ISSUE TITLE
Adapt Unit Tests to work with Auth

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#171]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [ ] Story is reviewed and accepted by PO
- [ ] Story is tested by DEV-Engineer
- [ ] Documentation extended if required

---

**Business value**
As a developer, I want to have a high test coverage, so that I feel confident that everything works.

**Description**

**Open points**

**Preconditions**

**Acceptance criterias**
- Tests work again

**Not in scope**

**Implementation details**

**Test case description**
Not needed.

**Involved contacts**
PO: @Andy-Bigler  
TE: @Andy-Bigler

**Comment by Andy-Bigler** [comment]
<img width="348" alt="image" src="https://user-images.githubusercontent.com/17875084/206892149-587daa28-a854-4110-acd1-af46cb3577ce.png">

**Comment by Andy-Bigler** [comment]
<img width="348" alt="image" src="https://user-images.githubusercontent.com/17875084/206897535-4b318357-8ade-4042-b09d-a92ed383156d.png">
