### ISSUE TITLE
UI: Create, update and delete a group

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#187]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [ ] Story is reviewed and accepted by PO
- [ ] Story is tested by DEV-Engineer
- [ ] Documentation extended if required

---

**Business value**
As a user, I want to group my habits in the UI too, so that I have a better overview.

**Description**

**Open points**

**Preconditions**

**Acceptance criterias**
- Group CRUD is implemented in UI

**Not in scope**

**Implementation details**

**Test case description**
Not needed.

**Involved contacts**
PO: @Andy-Bigler  
TE: @Andy-Bigler

**Comment by Andy-Bigler** [comment]
Not enough time left to do this. Will keep this as Postman only.
