### ISSUE TITLE
Update Figma Prototype for Group-Feature

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#188]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [ ] Story is reviewed and accepted by PO
- [ ] Story is tested by DEV-Engineer
- [ ] Documentation extended if required

---

**Business value**
As a user, I want to be able to group my habits so that I have a better overview.

**Description**

**Open points**

**Preconditions**

**Acceptance criterias**
- Group-Feature is added in Figma Prototype

**Not in scope**

**Implementation details**

**Test case description**
Not needed.

**Involved contacts**
PO: @Andy-Bigler  
TE: @Andy-Bigler

**Comment by Andy-Bigler** [comment]
Not needed as UI part will not be done
