### ISSUE TITLE
Show username instead of id on profile page

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#190]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [ ] Story is reviewed and accepted by PO
- [ ] Story is tested by DEV-Engineer
- [ ] Documentation extended if required

---

**Business value**
As a user, I want to see my username so that I remember it to log in again.

**Description**
Show username instead of id on profile page

**Open points**

**Preconditions**

**Acceptance criterias**
- Username is shown

**Not in scope**

**Implementation details**

**Test case description**
Not needed.

**Involved contacts**
PO: @Andy-Bigler  
TE: @Andy-Bigler

**Comment by janlauber** [comment]
![image](https://user-images.githubusercontent.com/31922734/208238528-0a504a4d-dde7-43cd-bee1-912ee9c3ac41.png)
