### ISSUE TITLE
Lean Canvas / Notes for end presentation

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#192]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [x] Story is reviewed and accepted by PO
- [x] Story is tested by DEV-Engineer
- [x] Documentation extended if required

---

**Business value**
As a developer, I want to now what problem we are solving so that I can communicate it to others.

**Description**
Create a lean canvas in Figma and prepare notes for the final presentation.

**Open points**

**Preconditions**

**Acceptance criterias**
- Lean canvas is created and agreed on by the team

**Not in scope**

**Implementation details**

**Test case description**
Not needed.

**Involved contacts**
PO: @Andy-Bigler  
TE: @Andy-Bigler

**Comment by Andy-Bigler** [comment]
https://www.figma.com/file/IZ2mwj2QtqESQ78ajo2tRp/Lean-Canvas?node-id=0%3A1&t=02NHNRwgf6EsRPoP-0

![image](https://user-images.githubusercontent.com/17875084/210826749-068257b4-91f0-44ae-9415-4bbb0bef3d6b.png)
