### ISSUE TITLE
Feature and vision documentation

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#194]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [ ] Story is reviewed and accepted by PO
- [ ] Story is tested by DEV-Engineer
- [ ] Documentation extended if required

---

**Business value**
As a user, I want to know what the application can do and why I should use it so that I can decide if I want to use it.

**Description**
Create a user documentation and write down the vision and problem being solved.

**Open points**

**Preconditions**

**Acceptance criterias**
- Readme's are written

**Not in scope**

**Implementation details**

**Test case description**
Not needed.

**Involved contacts**
PO: @Andy-Bigler  
TE: @Andy-Bigler

**Comment by janlauber** [comment]
added new menu point "info" which shows a simple user documentation about how to use the app.
Also added the vision part to the documentation.

**Comment by janlauber** [comment]
![image](https://user-images.githubusercontent.com/31922734/208240379-c0af073f-37f7-4006-83c6-aaa72ed9fd09.png)
![image](https://user-images.githubusercontent.com/31922734/208240388-479b59ee-0564-46fc-9f56-199b19188bfe.png)
