### ISSUE TITLE
Last deployment

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#208]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [x] Story is reviewed and accepted by PO
- [x] Story is tested by DEV-Engineer
- [x] Documentation extended if required

---

**Business value**
As a developer, I want to see the final version, so that I can deliver the project.

**Description**
Deploy final version of the project to be handed over.

**Open points**

**Preconditions**

**Acceptance criterias**
- Page is live on https://habits.gigu.io/

**Not in scope**

**Implementation details**

**Test case description**

**Involved contacts**
PO: @Andy-Bigler  
TE: @Andy-Bigler

**Comment by janfuhrer** [comment]
New Deployment successfully released
