### ISSUE TITLE
Final Presentation

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#209]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [x] Story is reviewed and accepted by PO
- [x] Story is tested by DEV-Engineer
- [x] Documentation extended if required

---

**Business value**
As a project group, we want to present the project, to get a good grade.

**Description**
Present final product and send the Scrum document.

**Open points**

**Preconditions**

**Acceptance criterias**
- Presentation is ready to be held
- Document is ready to be sent

**Not in scope**

**Implementation details**

**Test case description**

**Involved contacts**
PO: @Andy-Bigler  
TE: @Andy-Bigler

**Comment by janlauber** [comment]
@Andy-Bigler should be fine? done in figma
