### ISSUE TITLE
Try to setup the app with the Getting Started documentation

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#211]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [x] Story is reviewed and accepted by PO
- [x] Story is tested by DEV-Engineer
- [x] Documentation extended if required

---

**Business value**
As a developer, I want to have a simple and up to date getting started readme, so that I can setup my dev environment.

**Description**
Try out the getting started commands / documentation.

**Open points**

**Preconditions**

**Acceptance criterias**
- Frontend, Backend and Database can be started

**Not in scope**

**Implementation details**

**Test case description**

**Involved contacts**
PO: @Andy-Bigler  
TE: @Andy-Bigler

**Comment by Andy-Bigler** [comment]
Tested the following cases:
- Delete repo, clone it again and setup pre commit
- Without docker --> test and local profile
- Docker with manually built containers
- Docker with containers from registry
