### ISSUE TITLE
UI Create a habit

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#50]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [x] Story is reviewed and accepted by PO
- [x] Story is tested by DEV-Engineer
- [x] Documentation extended if required

---

**Business value**
As an enduser, I want to create a habit in the UI, so that I can track a new habit in the application.

**Description**
Create a habit in the UI.

**Open points**

**Preconditions**

**Acceptance criterias**

**Not in scope**

**Implementation details**

**Test case description**
Not needed.

**Involved contacts**
PO: @tonymowers 
TE: @janlauber

**Comment by janlauber** [comment]
implementing the following mockup component
![image](https://user-images.githubusercontent.com/31922734/198893652-e68621f7-df6b-420d-bf10-36c8025a94e0.png)

**Comment by janlauber** [comment]
also adding a default modal pop up component with the following form:
![image](https://user-images.githubusercontent.com/31922734/198893687-232e917c-9e64-4c6c-a157-ef895e818185.png)

also there are form components in it which i generalize

**Comment by janlauber** [comment]
Result:


![Image](https://user-images.githubusercontent.com/31922734/198897204-b96861e7-d91f-4ed6-be06-fade2f3ed8f8.png)



![Image](https://user-images.githubusercontent.com/31922734/198897213-0be4abee-4f17-4a86-88aa-a017c59525a3.png)

**Comment by janlauber** [comment]
@Andy-Bigler PO
please have a look and mark as done if good enough for you

**Comment by Andy-Bigler** [comment]
Thanks a lot. I also updated the backend to support the description.
Already checked it out and had a look.

**Comment by janlauber** [comment]
i commented out the weight section, bc the backend isn't ready for that in this sprint.
it looks now like:


![Image](https://user-images.githubusercontent.com/31922734/198974550-8ec93c0a-05a9-4c14-aa0c-15b3cc8cf57c.png)
