### ISSUE TITLE
UI Update a habit

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#51]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [ ] Story is reviewed and accepted by PO
- [ ] Story is tested by DEV-Engineer
- [ ] Documentation extended if required

---

**Business value**
As an enduser, I want to update a habit in the UI, so that I can update infos about the habit.

**Description**
Update a habit in the UI.

**Open points**

**Preconditions**

**Acceptance criterias**

**Not in scope**

**Implementation details**

**Test case description**
Not needed.

**Involved contacts**
PO: @tonymowers 
TE: @janlauber

**Comment by janlauber** [comment]
implementing the following component:
![image](https://user-images.githubusercontent.com/31922734/198970885-c910fe8a-a1fc-4faa-8b3a-45fa35b7a171.png)

**Comment by janlauber** [comment]
it looks now like:
![image](https://user-images.githubusercontent.com/31922734/198974306-b24832c0-e8c7-4b1d-9e4f-717a3a7d25fe.png)

**Comment by janlauber** [comment]
changed to english button text (also in create a habit #50 ):


![Image](https://user-images.githubusercontent.com/31922734/198974824-83490a5f-e3b0-45e4-ba79-36bcb507a9ac.png)
