### ISSUE TITLE
UI List all habits

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#54]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [x] Story is reviewed and accepted by PO
- [x] Story is tested by DEV-Engineer
- [x] Documentation extended if required

---

**Business value**
As an enduser, I want to list all habits in the UI, so that I can get infos about all tracked habits.

**Description**
List all habits in the UI.

**Open points**

**Preconditions**

**Acceptance criterias**

**Not in scope**

**Implementation details**

**Test case description**
Not needed.

**Involved contacts**
PO: @tonymowers 
TE: @janlauber

**Comment by janlauber** [comment]
Implementing the following Component in Next UI Frontend:
![image](https://user-images.githubusercontent.com/31922734/198889375-cfd1fbc6-ac68-4ebe-a93b-fb0a7033fd3a.png)

**Comment by janlauber** [comment]
Then we can add some testdata to show the following list like in the mockup:
![image](https://user-images.githubusercontent.com/31922734/198889446-0917ee41-4068-4169-af16-ed7f611b8d19.png)

**Comment by janlauber** [comment]
add a pencil Icon to edit or delete the habit:
![image](https://user-images.githubusercontent.com/31922734/198891922-b11076c1-0e99-48ff-8a69-6d0f438fbfa0.png)

**Comment by janlauber** [comment]
results:


![Image](https://user-images.githubusercontent.com/31922734/198897250-7e8fcbb3-57ed-4b96-b00d-73a3c5ebe939.png)
