### ISSUE TITLE
Create a figma prototype

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#60]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [x] Story is reviewed and accepted by PO
- [x] Story is tested by DEV-Engineer
- [x] Documentation extended if required

---

**Business value**
As an enduser, I want to use a cool and fancy UI, so that I like to use the application more and push myself to practice the habits.

**Description**
Create a Figma prototype of the UI.

**Open points**

**Preconditions**

**Acceptance criterias**

**Not in scope**

**Implementation details**

**Test case description**
Not needed

**Involved contacts**
PO: @tonymowers 
TE: @janlauber

**Comment by janfuhrer** [comment]
See Figma prototype on https://www.figma.com/file/DsA4OcnnPQibAHjJIvp9o7/Habit-Branding

**Comment by janlauber** [comment]
You can watch the current prototype under the following link:
https://www.figma.com/proto/DsA4OcnnPQibAHjJIvp9o7/Habit-Branding?node-id=23%3A3290&scaling=scale-down&page-id=0%3A1&starting-point-node-id=2%3A5

**Comment by janlauber** [comment]
@tonymowers any feedback on this prototype?

**Comment by tonymowers** [comment]
HI Jan,

I looked at the prototype and left some comments.   I see that you've closed this item. 
I'd recommend you reopen it.

**Comment by Andy-Bigler** [comment]
Feedback will be addressed here: #86
