### ISSUE TITLE
Adapt CI/CD for Kotlin

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#73]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [ ] Story is reviewed and accepted by PO
- [x] Story is tested by DEV-Engineer
- [x] Documentation extended if required

---

**Business value**
As an engineer, I want to have working Github workflows, so that I'm sure new commited code is working and tested as expected.

**Description**
Adapt all Github workflows to the new Kotlin implementation of the backend.

**Open points**

**Preconditions**

**Acceptance criterias**

**Not in scope**

**Implementation details**

**Test case description**
Not needed

**Involved contacts**
PO: @tonymowers 
TE: @janfuhrer

**Comment by janfuhrer** [comment]
includes #82
