### ISSUE TITLE
Improve figma prototype based on feedback

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#86]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [x] Story is reviewed and accepted by PO
- [x] Story is tested by DEV-Engineer
- [x] Documentation extended if required

---

**Business value**
As an enduser, I want to use a cool and fancy UI, so that I like to use the application more and push myself to practice the habits.

**Description**
Adapt the Figma prototype of the UI based on the feedback received.

**Open points**

**Preconditions**

**Acceptance criterias**

**Not in scope**

**Implementation details**
https://www.figma.com/proto/DsA4OcnnPQibAHjJIvp9o7/Habit-Branding?node-id=23%3A3290&scaling=scale-down&page-id=0%3A1&starting-point-node-id=2%3A5

**Test case description**
Not needed.

**Involved contacts**
PO: @tonymowers 
TE: @janlauber

**Comment by Andy-Bigler** [comment]
https://www.figma.com/proto/DsA4OcnnPQibAHjJIvp9o7/Habit-Branding?node-id=76%3A3403&scaling=scale-down&page-id=76%3A3297&starting-point-node-id=76%3A3298
