### ISSUE TITLE
Try out Spring Data and see if we could use it in the future

### ISSUE THREAD

**Issue by tonymowers** [bfhmea4/mea4_01_habits#87]
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [x] Story is reviewed and accepted by PO
- [x] Story is tested by DEV-Engineer
- [x] Documentation extended if required

---

**Business value**
As a developer, I want to be able to add new entities with CRUD functionality rapidly, so that we can offer many features to our customers.

**Description**
Try out Spring Data and see how we can use it for the project.

**Open points**

**Preconditions**

**Acceptance criterias**

**Not in scope**

**Implementation details**

**Test case description**
Not needed.

**Involved contacts**
PO: @tonymowers 
TE: @Andy-Bigler

**Comment by tonymowers** [comment]
Did you see my messages about this topic?

Please don't automatically start migrating to Spring Data Rest API without discussing it more.   I demonstrated the technology, but that does not mean you have to use it.   There could be some potential risks to using it.

It would be acceptable to me if you used the Controllers/Services/Tests approach that you've already implemented for the habit class and did not try to use Spring Data Rest framework.

I'd like us to talk about this more before you invest any time in this migration.

**Comment by tonymowers** [comment]
@Andy-Bigler it's my understanding from the email then that you will go forward with the UI using the Controllers/Services endpoint rather than the Spring Data Rest endpoint.  And if more entities /tables are added then you will revisit the Spring Data Rest to investigate it more.

**Comment by Andy-Bigler** [comment]
I just spend a few hours trying out Spring Data. For SELECT queries it looks amazing and it is even possible to generate new queries based on custom functions that you can add in the Repository Interfaces. But I struggled so much with everything which was not GET... Maybe I'm missing something. For now I would stick to the current approach with writing the controllers ourselves.
